import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service',
}

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-16">
      <h1 className="text-3xl font-semibold text-gray-900 mb-2">Terms of Service</h1>
      <p className="text-sm text-gray-400 mb-10">Last updated: February 27, 2026</p>

      <div className="prose prose-gray max-w-none [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:text-gray-900 [&_h2]:mt-10 [&_h2]:mb-4 [&_p]:text-gray-600 [&_p]:leading-relaxed [&_p]:mb-4 [&_ul]:text-gray-600 [&_ul]:mb-4 [&_li]:mb-1">
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using Bloom (&ldquo;the Service&rdquo;), operated by Bloom (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          Bloom is a collaborative software platform where users contribute ideas to open source projects and AI agents implement those ideas as code changes, pull requests, and shipped features. The Service includes web interfaces, APIs, and AI agent systems.
        </p>

        <h2>3. Account Registration</h2>
        <p>
          You may register using email/password or GitHub OAuth. You are responsible for maintaining the confidentiality of your account credentials. You must provide accurate information and keep it up to date. You must be at least 13 years old to use the Service.
        </p>

        <h2>4. User Content</h2>
        <p>
          &ldquo;User Content&rdquo; includes ideas, messages, feedback, and any other content you submit through the Service. You retain ownership of your User Content. By submitting User Content, you grant us a worldwide, non-exclusive, royalty-free license to use, reproduce, and display your content in connection with operating and improving the Service.
        </p>
        <p>
          Ideas submitted to public projects may result in open source code contributions. By submitting ideas to public projects, you acknowledge that resulting code will be published under the project&apos;s open source license.
        </p>

        <h2>5. AI-Generated Code</h2>
        <p>
          Code generated by AI agents in response to user ideas is contributed to the relevant project under that project&apos;s open source license. We do not claim ownership of AI-generated code contributed to your private projects. AI-generated output is provided &ldquo;as is&rdquo; without warranty of fitness for any particular purpose.
        </p>

        <h2>6. Subscription and Billing</h2>
        <p>
          Bloom offers free and paid tiers. Paid subscriptions are billed monthly through Stripe. You may cancel at any time. Cancellation takes effect at the end of the current billing period. Refunds are handled on a case-by-case basis. Sponsorship payments support specific projects and are non-refundable.
        </p>

        <h2>7. BYOK (Bring Your Own Key)</h2>
        <p>
          If you provide your own API key (e.g., Anthropic API key), you are responsible for all charges incurred through that key. We store your key securely and use it only to execute agent tasks on your behalf. You may remove your key at any time.
        </p>

        <h2>8. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service for illegal purposes or to violate any laws.</li>
          <li>Submit malicious code, prompts designed to exploit AI agents, or content that could harm other users or projects.</li>
          <li>Attempt to circumvent rate limits, usage quotas, or security measures.</li>
          <li>Impersonate other users or misrepresent your affiliation.</li>
          <li>Scrape, crawl, or automated access the Service beyond normal API usage.</li>
        </ul>

        <h2>9. Intellectual Property</h2>
        <p>
          The Bloom platform, including its design, code, and branding, is owned by us. Open source components are licensed under their respective licenses. Nothing in these terms grants you rights to our trademarks, logos, or brand assets.
        </p>

        <h2>10. Limitation of Liability</h2>
        <p>
          The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind. We are not liable for any damages arising from your use of the Service, including but not limited to loss of data, business interruption, or AI agent errors. Our total liability is limited to the amount you paid us in the 12 months preceding the claim.
        </p>

        <h2>11. Termination</h2>
        <p>
          We may suspend or terminate your account at our discretion for violations of these terms. You may delete your account at any time. Upon termination, your right to use the Service ceases immediately. Provisions that should survive termination (including limitation of liability) will survive.
        </p>

        <h2>12. Changes to Terms</h2>
        <p>
          We may update these terms from time to time. We will notify users of material changes via email or in-app notice. Continued use of the Service after changes constitutes acceptance of the updated terms.
        </p>

        <h2>13. Contact</h2>
        <p>
          Questions about these terms? Reach us at{' '}
          <a href="mailto:support@bloomit.ai" className="text-gray-900 underline underline-offset-2 hover:text-gray-600">
            support@bloomit.ai
          </a>.
        </p>
      </div>

      <div className="mt-12 pt-8 border-t border-gray-100 text-sm text-gray-400">
        <Link href="/privacy" className="hover:text-gray-600 transition-colors">
          Privacy Policy &rarr;
        </Link>
      </div>
    </div>
  )
}
